### ISSUE TITLE
Crash Solution Explorer > Solution > 'Solution Folder' > Right Click (Context Menu) crashes visual studio.

### ISSUE THREAD

**Issue by MichielNL83** [OsamaAbuSitta/AngularVSExtension#1]
### Installed product versions
- Visual Studio: 2022 enterprise
- This extension: 2.0

### Description
In solution explorer >trying to open context menu on item in solution folder crashes visual studio.

### Steps to recreate
1. Create Solution
2. Create 'Solution Folder'
3. Add Existing Item to created solution folder
4. right click on added file

### Current behavior
trying to open context menu on item in solution folder crashes visual studio.

**Comment by OsamaAbuSitta** [comment]
thanks @MichielNL83 for reporting this issue , now it fixed and uploaded please try the new version
